[build]
  command = "cd ./functions/ && npm install node-fetch"
and i

[functions]
  directory = "functions/"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect?url=:splat"
  status = 200
  force = true
